import React from "react";

const Card1 = () => {
  return (
    <div className="card">
      <div class="container">
        <p>
          PRIMARY RESOURCES ALL HISTORY ANCIENT GREEKS ANCIENT EGYPTIANS ANGLO
          SAXONS, VIKINGS & NORMANS AZTECS, MAYA & INCA ROMANS SIGNIFICANT
          EVENTS SIGNIFICANT PEOPLE STONE AGE TO IRON AGE THE MONARCHY SCIENCE
          ANIMALS & INSECTS DINOSAURS EVOLUTION FORCES HABITATS HUMANS PLANTS
          ROCKS SPACE GEOGRAPHY ENVIRONMENT PEOPLE PLACES WATER CYCLE WEATHER
          ENGLISH COMPREHENSION GRAMMAR & PUNCTUATION PHONICS READING SPELLING
          WRITING MATHS COUNTING GAMES GEOMETRY MEASURING ART & DESIGN ARTISTS
          CRAFTS D&T MUSIC PAINTING PSHE ACTIVITIES BRITISH VALUES CAREERS
          FESTIVALS FUN FACTS NUTRITION PE WEIRD & WONDERFUL
        </p>
      </div>
    </div>
  );
};

export default Card1;
